### ISSUE TITLE
[Task] step1. data preparation

### ISSUE THREAD

**Issue by kyungjaecheong** [kyungjaecheong/Seoul-FP-Weather#2]
## Task Card

**Assignee** : kyungjaecheong

#### Job Description
> 작업 내용을 적어주세요

- [x] 식품의약품안전처 Open API 인증 키 얻은 후 URL주소 .env 에 저장
- [x] 서울 열린 데이터 광장에서 서울시 월 별 기상 개황 자료 다운로드(csv)
- [x] 다운 받은 데이터를 RDB로 넣을 수 있는 형태로 가공(jupyter)
