### ISSUE TITLE
[Task] step1-2. RDB -> CloudDB -> localDB

### ISSUE THREAD

**Issue by kyungjaecheong** [kyungjaecheong/Seoul-FP-Weather#3]
## Task Card

**Assignee** : kyungjaecheong

#### Job Description
> 작업 내용을 적어주세요

- [x] AWS RDS 계정 생성, CloudDB for postgreSQL 구축
- [x] postgreSQL host 및 password를 .env에 저장
- [x] postgreSQL로 RDB 스키마 구축, 데이터 입력
- [x] SQL query를 통해 table join 후 csv로 저장
