### ISSUE TITLE
[Task] Step3-2. Flask & HTML

### ISSUE THREAD

**Issue by kyungjaecheong** [kyungjaecheong/Seoul-FP-Weather#9]
## Task Card

**Assignee** : kyungjaecheong

#### Job Description
> 작업 내용을 적어주세요

- [x] Flask 구동 file 생성 (app.py)
- [x] HTML & CSS 생성 - bootstrap
- [x] Error page 생성
- [x] icon 제작
- [x] index.html 및 css file 완성 - 홈페이지 구현
- [x] 웹페이지에 대시보드 구현
- [x] 모바일 최적화 진행
- [x] 웹페이지 테스트
